apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: thanos-sidecar
    app.kubernetes.io/instance: user-workload
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 2.50.1
  name: thanos-sidecar
  namespace: openshift-user-workload-monitoring
spec:
  endpoints:
  - bearerTokenFile: ""
    interval: 30s
    port: thanos-proxy
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
      insecureSkipVerify: false
      keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
      serverName: prometheus-user-workload-thanos-sidecar.openshift-user-workload-monitoring.svc
  selector:
    matchLabels:
      app.kubernetes.io/component: thanos-sidecar
