apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.thanos-ruler-: ""
  labels:
    app.kubernetes.io/component: rule-evaluation-engine
    app.kubernetes.io/instance: thanos-ruler
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: thanos-rule
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 0.37.2
  name: thanos-ruler
  namespace: openshift-user-workload-monitoring
